[package]
name = "client"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.87"
bincode = "1.3.3"
constrained-inputs = "0.1.2"
iced = {version="0.12.1", features=["advanced"]}
serde = {version="1.0.210", features = ["derive"]}
