[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.87"
bincode = "1.3.3"
rand = "0.8.5"
serde = {version="1.0.210", features = ["derive"]}
tokio = { version = "1.4", features = ["full"] }
